version: '2'
services:
    test789svc-app:
        image: test789svc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://test789svc-postgresql:5432/test789svc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    test789svc-postgresql:
        extends:
            file: postgresql.yml
            service: test789svc-postgresql
